### ISSUE TITLE
Install Task Error 

### ISSUE THREAD

**Issue by calebcartwright** [Microsoft/vsts-extension-build-release-tasks#61]
I'm getting a fatal error from the `Install Extension` task (version `1.1.61`) . I'm fairly confident this is related to an underlying issue in the TFS CLI (v0.5.4) as there's a [related issue opened in the TFS CLI repo](https://github.com/Microsoft/tfs-cli/issues/253) with the same error message:

```
 error: Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.
```

Opening this issue here both for awareness that the `Install Extension` task appears to be broken, and to see if there is some interim workaround (for example using an earlier version of the TFS CLI, using v0.* of this extension, etc.) of this extension that can be used while the underlying TFS CLI issue is resolved.

**Comment by jessehouwing** [comment]
Has this been fixed in 0.5.5 that was just released?

**Comment by calebcartwright** [comment]
I am still getting the error in the `Install Extension` task, although it is still using the CLI v0.5.4 under the hood. What's the best way to pull in 0.5.5 (on my private agents)?

**Comment by jessehouwing** [comment]
Delete the _tools folder in the agent workfolder. It'll pull in the new
version on the next build.

**Comment by calebcartwright** [comment]
The error still exists with v0.5.5 of the cli:

018-03-08T17:50:31.3178521Z error: Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.
2018-03-08T17:50:31.3191492Z TFS Cross Platform Command Line Interface **v0.5.5**
2018-03-08T17:50:31.3213148Z Copyright Microsoft Corporation
2018-03-08T17:50:31.3749328Z ##[error]Failed
2018-03-08T17:50:31.3808601Z ##[section]Finishing: Install Extension

**Comment by MarkusRich** [comment]
The error still exists in v0.5.6

FS Cross Platform Command Line Interface v0.5.6
Copyright Microsoft Corporation
2018-03-09T13:11:04.045Z : extensioninfo.getExtInfo
2018-03-09T13:11:04.057Z : c:\example.vsix
2018-03-09T13:11:04.063Z : Read vsix as zip... Size (bytes): 2183793
2018-03-09T13:11:04.065Z : Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.
2018-03-09T13:11:04.065Z :     at new JSZip (c:\npm\node_modules\tfx-cli\node_modules\jszip\lib\index.js:14:15)
2018-03-09T13:11:04.065Z :     at c:\npm\node_modules\tfx-cli\_build\exec\extension\_lib\extensioninfo.js:59:20
2018-03-09T13:11:04.065Z :     at <anonymous>
error: Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.

**Comment by calebcartwright** [comment]
The problem is on line 34 of `extensioninfo` in the cli: https://github.com/Microsoft/tfs-cli/blob/master/app/exec/extension/_lib/extensioninfo.ts#L34

I was going to send a pull with the fix, but I couldn't get the tfs cli code to build from source with the instructions provided.. If anyone can, the fix should be pretty easy (the fix was made elsewhere in the CLI codebase where `jszip` is used, so there are plenty of examples)

**Comment by jessehouwing** [comment]
@trevorsg THis fixed in the latest drop?

**Comment by trevorsg** [comment]
I don't think so
